import type { Deck } from "@/domain/cards";

const now = new Date().toISOString();

export const starterDecks: Deck[] = [
  {
    id: "deck-writing-cn",
    name: "Writing Booster",
    description: "Turn rough drafts into concise publish-ready copy.",
    target: "hermes",
    version: "1.0.0",
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        type: "model",
        id: "model-openrouter-qwen",
        title: "Balanced Writer Model",
        provider: "openrouter",
        model: "qwen/qwen3-32b",
        temperature: 0.7,
        maxTokens: 2400,
      },
      {
        type: "soul",
        id: "soul-writing",
        title: "Editorial Soul",
        persona: "a senior editor for startup product teams",
        tone: "friendly",
        language: "zh-TW",
        safetyLevel: "normal",
        boundaries: [
          "No fabricated claims or data.",
          "Show assumptions when context is missing.",
        ],
      },
      {
        type: "memory",
        id: "memory-writing",
        title: "Session Memory",
        mode: "session",
        retentionDays: 3,
        tokenLimit: 3000,
      },
    ],
  },
  {
    id: "deck-support-seller",
    name: "Ecommerce Support",
    description: "Generate polite customer support replies with policy guardrails.",
    target: "hermes",
    version: "1.0.0",
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        type: "model",
        id: "model-openrouter-gpt",
        title: "Support Reply Model",
        provider: "openrouter",
        model: "openai/gpt-4.1-mini",
        temperature: 0.4,
        maxTokens: 1800,
      },
      {
        type: "soul",
        id: "soul-support",
        title: "Customer Support Soul",
        persona: "a careful support specialist",
        tone: "calm",
        language: "zh-TW",
        safetyLevel: "strict",
        boundaries: [
          "Never promise unavailable compensation.",
          "Always cite policy assumptions explicitly.",
        ],
      },
      {
        type: "tool",
        id: "tool-knowledge-base",
        title: "Policy Search",
        toolId: "knowledge_base.search",
        approval: "ask",
        scope: ["refund_policy", "shipping_policy"],
        rateLimitPerMinute: 12,
      },
      {
        type: "memory",
        id: "memory-support",
        title: "Persistent Memory",
        mode: "persistent",
        retentionDays: 30,
        tokenLimit: 6000,
      },
    ],
  },
  {
    id: "deck-research-lite",
    name: "Research Scout",
    description: "Create fast research summaries with explicit confidence boundaries.",
    target: "hermes",
    version: "1.0.0",
    createdAt: now,
    updatedAt: now,
    cards: [
      {
        type: "model",
        id: "model-openrouter-anthropic",
        title: "Research Model",
        provider: "openrouter",
        model: "anthropic/claude-3.7-sonnet",
        temperature: 0.3,
        maxTokens: 3200,
      },
      {
        type: "soul",
        id: "soul-research",
        title: "Research Soul",
        persona: "an analyst producing concise evidence summaries",
        tone: "assertive",
        language: "en",
        safetyLevel: "strict",
        boundaries: [
          "Tag uncertain statements as tentative.",
          "Separate facts from interpretation.",
        ],
      },
      {
        type: "skill",
        id: "skill-sources",
        title: "Citation Skill",
        skillId: "citation.annotate",
        enabled: true,
        visibility: "private",
        config: {
          outputFormat: "markdown",
          includeConfidence: true,
        },
      },
      {
        type: "memory",
        id: "memory-research",
        title: "Session Memory",
        mode: "session",
        retentionDays: 5,
        tokenLimit: 5000,
      },
    ],
  },
];
